# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rishi E. Kumar
title: PhD Candidate
email: rishi42@gmail.com
website: rekumar.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: rekumar_
github_username:  rekumar
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: rekumar
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: 
# orcid_username:  0000-0002-1993-9275

# Additional icon links
additional_links:
- title: google scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=nVzy5csAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/REK.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rishi and I am researching high-throughput discovery and optimization of photovoltaic materials at UC San Diego.
  I bridge hardware, software, and materials expertise to automate material science research.
  Additionally, I have developed spatially resolved metrology techniques for [benchtop](https://ieeexplore.ieee.org/abstract/document/8854288) and [synchrotron](https://link.springer.com/article/10.1557/s43580-021-00114-0) characterization of photovoltaics. 

  I am most skilled in: <mark>Materials Characterization</mark>, <mark>Lab Automation</mark>, and <mark>Python</mark>.

  Get my CV [here](assets/20220130_RishiEKumar_CV.pdf).

content:
  - title: Code for Lab Automation # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Roboflo
        # link: github.com/rekumar/roboflo
        # link_text: Project Website
        additional_links:
          - title:  rekumar/roboflo
            icon: fab fa-github
            url: github.com/rekumar/roboflo
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          [![Roboflo](https://github.com/rekumar/mixsol/raw/main/docs/mixsol.svg)](github.com/rekumar/roboflo)
          Task scheduler for any system with coordinated workers. The original use case is for the Perovskite Automated Solar Cell Assembly Line (PASCAL) in the Fenning Lab at UC San Diego, where a robotic arm moves small glass slides between stations to perform experiments.
      
      - layout: top-middle
        title: MixSol
        link: github.com/rekumar/mixsol
        # link_text: Project Website
        additional_links:
          - title:  rekumar/mixsol
            icon: fab fa-github
            url: github.com/rekumar/mixsol
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          Pipetting planner for efficient combinatorial mixing of solutions. Often we want to interpolate a few stock solutions into many target mixtures. If some of these mixtures require only a tiny amount of a stock solution, the minimum volume for our pipette may limit our ability to make this solution without a serial dilution. Mixsol searches for mixing sequences that use only other target solutions as stepping stones to reach these difficult mixtures, minimizing waste.

      - layout: top-middle
        title: PASCAL
        link: https://github.com/fenning-research-group/PASCAL
        # link_text: Project Website
        additional_links:
          - title:  fenning-research-group/PASCAL
            icon: fab fa-github
            url: https://github.com/fenning-research-group/PASCAL
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          The Perovskite Automated Solar Cell Assembly Line (PASCAL) at the Fenning Lab in UC San Diego. Spin-coats and characterizes optoelectronic thin films, constructs solar cells, and executes closed-loop active learning optimization campaigns. A constant work in progress!

          Check it out in action [here](https://youtu.be/dKTjTsvgrgU) and [here](https://youtu.be/l_-ezXn_QaU)!
      

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fenning Lab at UC San Diego
        link: fenningresearchgroup.com
        # link_text: boringcompany.com
        sub_title: PhD Candidate
        caption: 2017 - Present
        # quote: >
          
        description: | # this will include new lines to allow paragraphs
          Worked on a variety of research topics related to photovoltaics (PV), with an emphasis on doing faster science. Built a robot to do high-throughput compositional search and/or process optimization for halide perovskite thin films. Used machine learning to guide the robot to do the right experiments. 
          Developed a method to measure water in silicon PV modules without taking them apart, used that to study local effects of water on performance loss. Did a lot of synchrotron characterization of halide perovskite composition and structure. 

      - layout: left
        title: Nanocomposix
        link: nanocomposix.com
        # link_text: boringcompany.com
        sub_title: Research Associate II
        caption: 2015-2017
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Made pyrophoric confetti to mimic the heat signature of specific aircraft to distract advanced heat-seaking arms. Controlled the size and shape of silver nanoparticle to selectively absorb common laser wavelengths for skincare applications. Led the scaleup of this nanoparticle synthesis from 5 mL to 55 gallon batch sizes.
  
  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Harvard University
  #       caption: 2010 - 2013
  #       sub_title: BSc Computer Science
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-slate